dataset:
    class : ts
    path  : ./data/
    filename : RHHBY.csv
    datetime_col  : Date
    value_col : Close
    time_window : 30
workers : 0                         #number of data loading workers
batch_size : 16                     #input batch size
nz: 100                             #dimensionality of the latent vector z
epochs : 70                         #number of epochs to train for
lr : 0.0002                         #learning rate
cuda : True                         #enables cuda
#netG :                             #path to netG (to continue training)
#netD :                             #path to netD (to continue training)
outf : checkpoints                  #folder to save checkpoints
imf : images                        #folder to save images
logdir : log                        #logdir for tensorboard
run_tag : test_CNN_dis_LSTM_gen     #tags for the current run
checkpoint_every : 5                #number of epochs after which saving checkpoints
tensorboard_image_every : 5         #interval for displaying images on tensorboard 
delta_condition : True              #whether to use the mse loss for deltas
delta_lambda : 10                   #weight for the delta condition
alternate : True                    #whether to alternate between adversarial and mse loss in generator
dis_type : cnn                      #choices=['cnn','lstm'], architecture to be used for discriminator to use
gen_type : lstm                     #choices=['cnn','lstm'], architecture to be used for generator to use
#output_path : ./output
deltas : [0.1, 0.2, 0.3, 0.05]
size : 100
outfile : ./test_CNN_dis_LSTM_gen.npy



